### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by Martin005** [TechFides/tf-licence-checker#2]
There is currently no license set for this package, it would be great to use one 😉

**Comment by fladr** [comment]
There is licence set in package.json https://github.com/TechFides/tf-licence-checker/blob/master/package.json#L22. You mean LICENCE file?

**Comment by Martin005** [comment]
@fladr Yes, exactly.

**Comment by fladr** [comment]
File was uploaded in version 1.1.9
